digitalverse/hubs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # url(r'^$', views.BrowseView.as_view(), name='post-list'),


    url(r'^create-hub/$', views.HubCreate.as_view(), name='hub-create'),
    url(r'^hub/(?P<slug>[^\.]+)/edit$', views.HubEdit.as_view()),
    url(r'^hub/(?P<slug>[^\.]+)/delete$', views.hub_delete),    

    # url(r'^browse/$', views.BrowseView.as_view(), name='post-list'),

    url(r'^hub/(?P<slug>[^\.]+)/subscribe', views.subscribe),
    url(r'^hub/(?P<slug>[^\.]+)/unsubscribe', views.unsubscribe),    

    
    url(r'^hub/(?P<slug>[^\.]+)$', views.HubView.as_view(), name='hub-detail'),


    url(r'^hubs/', views.HubsBrowse.as_view()),
    
]

digitalverse/lumiverse/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from posts import urls as posts_urls
from videos import urls as videos_urls
from series import urls as series_urls
from hubs import urls as hubs_urls
from profiles import urls as profiles_urls
from comments import urls as comments_urls
# from forum import urls as forum_urls

from .views import about, lumen, rigs

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^about/', about),
    url(r'^lumen/', lumen),
    url(r'^rigs/', rigs),            

    url(r'', include(profiles_urls)),        
    url(r'', include(posts_urls)),
    url(r'', include(videos_urls)),    
    url(r'', include(series_urls)),
    url(r'', include(hubs_urls)),        
    url(r'', include(comments_urls)),
    # url(r'', include(forum_urls)),    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

digitalverse/profiles/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout

from .views import login_or_signup, register, authenticate_user, preferences, update_password, about, subscribe, unsubscribe

urlpatterns = [
    url('^login/$', login_or_signup),
    url(r'^logout/', logout), # , {'next_page':'/'}

    url('^register/$', register),
    url(r'^authenticate/', authenticate_user),

    url(r'^preferences/$', preferences),
    # url(r'^user/(?P<slug>[^\.]+)/preferences$', views.UserEdit.as_view()),    
    url(r'^update-password/$', update_password),

    url(r'^user/(?P<username>[^\.]+)/about$', about),        

    url(r'^user/(?P<username>[^\.]+)/subscribe', subscribe),
    url(r'^user/(?P<username>[^\.]+)/unsubscribe', unsubscribe),    
]

digitalverse/profiles/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models import permalink

from django.core.files.base import ContentFile
from sorl.thumbnail import ImageField
from sorl.thumbnail import get_thumbnail

# from posts.models import Post
from series.models import Series

class User(AbstractUser):  
    avatar = models.ImageField(upload_to='users/avatars/', default=None,blank=True, null=True)
    background = models.ImageField(upload_to='users/backgrounds/', default=None,blank=True, null=True)
    about = models.TextField(max_length=512, blank=True)
    website = models.CharField(max_length=64, blank=True)
    youtube_channel = models.CharField(max_length=128, blank=True)    

    karma = models.IntegerField(default=0)
    # created = models.DateTimeField(auto_now_add=True, blank=True)

    subscribed = models.ManyToManyField('User', related_name="subscribers", blank=True)
    subscribed_series = models.ManyToManyField('series.Series', related_name="subscribers", blank=True)    

    upvoted = models.ManyToManyField('videos.Video', related_name="upvoters", blank=True)
    posts_upvoted = models.ManyToManyField('posts.Post', related_name="upvoters", blank=True)
    comments_upvoted = models.ManyToManyField('comments.Comment', related_name="upvoters", blank=True)

    newsletter = models.BooleanField(default=False)    
    approved = models.BooleanField(default=False)
    hidden = models.BooleanField(default=False)

    youtube_player = models.BooleanField(default=False)        
    
    # @permalink
    # def get_absolute_url(self):
    #     return ('view_post', None, {'slug': self.slug })        

    # def save(self, slug="", *args, **kwargs):
    #     super(User, self).save(*args, **kwargs)  
    #     resized = get_thumbnail(self.avatar, "120x120", crop='center', quality=99)
    #     self.avatar.save(resized.name, ContentFile(resized.read()), True)            

    #     return super(User, self).save(*args, **kwargs)
    

digitalverse/profiles/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import User

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=False, widget=forms.TextInput(attrs = {'placeholder': 'E-Mail'})) #reqired=True

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2", "newsletter")
        widgets = {
            'username' : forms.TextInput(attrs = {'placeholder': 'Username'}),
            'email'    : forms.TextInput(attrs = {'placeholder': 'E-Mail'}),
            # 'newsletter'    : forms.CheckboxInput(attrs = {'placeholder': 'E-Mail'}),
            # These don't work, had to redefine in views(login_or_signup)
            # 'password1' : forms.PasswordInput(attrs = {'placeholder': 'Password'}),
            # 'password2' : forms.PasswordInput(attrs = {'placeholder': 'Repeat Password'})
        }

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user
        
class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'newsletter', 'avatar', 'background', 'website', 'youtube_channel', 'about']
        widgets = {
            'username' : forms.TextInput(attrs = {'placeholder': 'Username'}),
            'email'    : forms.TextInput(attrs = {'placeholder': 'E-Mail'}),
            'website'    : forms.TextInput(attrs = {'placeholder': 'Website'}),
            'youtube_channel'    : forms.TextInput(attrs = {'placeholder': 'Youtube Channel Url'}), 
            'about'    : forms.Textarea(attrs = {'placeholder': 'About'}),
        }
    

digitalverse/profiles/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView, UpdateView

from .models import User
from .forms import RegistrationForm, UserForm



def subscribe(request, username):
    userprofile = User.objects.get(username=username)
    if not request.user.is_anonymous():
        user = request.user
        user.subscribed.add(userprofile)
        user.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER')) 
    else:
        return HttpResponseRedirect('/login/')    

def unsubscribe(request, username):
    userprofile = User.objects.get(username=username)    
    user = request.user
    user.subscribed.remove(userprofile)
    user.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER')) 
    

def login_or_signup(request):
    # If already logged in - get out of here
    if request.user.is_authenticated():
        return HttpResponseRedirect('/')

    nextpage = request.GET.get('next', '/')
    authenticate_form = AuthenticationForm(None, request.POST or None)
    # register_form = UserCreationForm()
    register_form = RegistrationForm()
    register_form.fields['password1'].widget.attrs['placeholder'] = "Password"
    register_form.fields['password2'].widget.attrs['placeholder'] = "Repeat Password"        
    return render(request, "profiles/login.html", {
        'authenticate_form': authenticate_form,
        'register_form': register_form,
        'nextpage': nextpage,                
    })


# Only log in
def authenticate_user(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/')
 
    # Initialize the form either fresh or with the appropriate POST data as the instance
    auth_form = AuthenticationForm(None, request.POST or None)
    nextpage = request.GET.get('next', '/')
 
    # The form itself handles authentication and checking
    # to make sure passowrd and such are supplied.
    if auth_form.is_valid():
        login(request, auth_form.get_user())
        return HttpResponseRedirect(nextpage)
 
    return render(request, 'profiles/form-invalid.html', {
        'form': auth_form,
        'title': 'User Login',
        'next': nextpage,
    })

# Only sign up
def register(request):
    rational = False
    if request.META['HTTP_HOST'] == "rationalfiction.io" or \
       request.META['HTTP_HOST'] == "localhost:8000":
        rational = True

    if request.method == 'POST':
        # form = UserCreationForm(request.POST)
        form = RegistrationForm(request.POST)
        if form.is_valid():
            # new_user = form.save()
            user = User.objects.create_user(form.cleaned_data['username'], None, form.cleaned_data['password1'])
            user.email = form.cleaned_data['email']
            user.newsletter = form.cleaned_data['newsletter']            

            user.save()

            # log user in after signig up
            username = request.POST['username']
            password = request.POST['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            
            return HttpResponseRedirect("/")
    else:
        form = UserCreationForm()
    return render(request, "profiles/form-invalid.html", {
        'form': form,
    })


@login_required
def preferences(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login/')

    message = ""    

    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/preferences/')
        else:
            message="error"
    else:
        form = UserForm(instance=request.user)
    
    return render(request, "profiles/preferences.html", {
        'form': form,
        'message':message
    })



# class UserEdit(UpdateView):
#     model = User
#     slug_field = 'username'
#     fields = ["username","avatar"]
#     template_name = 'profiles/test.html'

#     def get_success_url(self):
#         return "/user/rayalez/preferences"
#         # return self.request.path


@login_required
def update_password(request):
    form = PasswordChangeForm(user=request.user)
    message = ""

    if request.method == 'GET':
        if request.GET.get('error')=="1":
            message = "Error, please try again."

    if request.method == 'POST':
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return HttpResponseRedirect('/preferences/')
        else:

            return HttpResponseRedirect('/update-password/?error=1')            
    else:
        form = PasswordChangeForm(user=request.user)

    return render(request, "profiles/update-password.html", {
        'form': form,
        'message':message
    })



def about(request, username):
    userprofile = User.objects.get(username=username)    

    return render(request, 'profiles/about.html',{
        'userprofile':userprofile
    })

digitalverse/templates/profiles/about.html
{% extends "base.html" %}
{% load markdownify %}
{% block content %}
    
<div id="page"  class="postPage profile">
  {% include "elements/subheader.html" %}

  <div class="row">
    <div class="large-12 columns">
      <article>
	<header class="post-header">
	  <h1> About </h1>
	  <hr />
	</header>
	{{userprofile.about| markdownify | safe }}
	<br/>
	<div>
      </article>
      </div> <!-- End 12 columns -->
    </div> <!-- End row -->
  </div>
</div>

<style>
  .about {
  font-weight:bold!important;
  color:#3d454b!important;
  }


</style>
{% endblock content %}

digitalverse/templates/profiles/form-invalid.html
{% extends "base.html" %}
{% block content %}

<div id="page"  class="postPage">
  <div class="row">
    <div class="large-12 columns">
      <!-- Login -->
      <h2> Error </h2>
      {% if form.errors %}
      {{form.errors.message}}
      {% endif %}
      <form method="post"
	    {% if title == "User Login" %}
	    action="/authenticate/"
	    {% else %}
	    action="/register/"	    
	    {% endif %}      	    
	    > {% csrf_token %}
	{{form}}
	<button class="button small" type="submit">Submit</button>	
      </form>
  </div>	 <!-- End row -->
</div>

{% endblock content %}

digitalverse/templates/profiles/login.html
{% extends "base.html" %}
{% block content %}

<div id="page"  class="postPage">
  <div class="row">
    <div class="large-5 columns">
      <!-- Login -->
      <h2> Login </h2>
      {% if authenticate_form.errors %}
      <p>Your username and password didn't match. Please try again.</p>
      {% endif %}
      
      <form method="post" action="/authenticate/?next={{nextpage}}"> {% csrf_token %}
	{{authenticate_form}}
	<input type="submit" class="button small" value="login" />
	<input type="hidden" name="next" value="{{ next }}" />
      </form>
    </div>
    
    <div class="large-5 columns">
      <!-- Register -->
      <h2> Sign Up </h2>
      <form method="post" action="/register/?next={{nextpage}}"> {% csrf_token %}
	{{register_form.username}}
	{{register_form.email}}
	{{register_form.password1}}
	{{register_form.password2}}
	<input type="submit" class="button small" value="submit" />
	<input type="hidden" name="next" value="{{ next }}" />
	<div class="clearfix"></div>
	<div style="width:100%; height: 20px"></div>
	<br/>
      </form>    
    </div>
  </div>	 <!-- End row -->
</div>

{% endblock content %}

digitalverse/templates/profiles/preferences.html
{% extends "base.html" %}
{% load thumbnail %}

{% block content %}

<div class="row">
  <div class="large-12 columns">
    <h1> Preferences </h1>
    <br/>
    {% if message %}
    <br/>
    <div class="panel">{{message}}</div>
    {% endif %}
    <form method="post" enctype="multipart/form-data" action="/preferences/">{% csrf_token %}
      Username:
      {{form.username}}
      {{form.email}}
      <!-- Newsletter -->
      <div class="newsletter-checkbox">
	<input type="checkbox" name="newsletter" id="newsletter" class="css-checkbox"
	       {% if user.newsletter %}checked{%endif%}/>
	<label for="newsletter" class="css-label checkbox-label"
	        style="margin: 0;
		       margin-bottom: 14px;">
	  Receive weekly newsletter (tutorials, articles, updates, no spam).
	</label>
      </div>
      {{form.website}}



      <!-- Avatar -->
      {% if not user.avatar %}      
      Avatar:
      <div id="image-filechoice-container">
	<input id="id_avatar" name="avatar" type="file">      
      </div>
      <a id="upload" class="small button"><i class="fa fa-upload"></i>&nbsp; Image</a>
      {% else %}
      <!-- Avatar Thumbnail -->
      <div style="width:70px;
		  height:70px;
		  float:left;
		  margin-right:10px;">
	{% thumbnail user.avatar "70x70" crop="center" as im %}
	    <img src="{{im.url}}"/><br/>
	{% endthumbnail %}	  
      </div>
      <!-- Repace Avatar -->
      Avatar:
      <div id="image-filechoice-container"
	   style="width:calc(100% - 80px);">
	<input id="id_avatar" name="avatar" type="file">      
      </div>
      <a id="upload" class="small button"><i class="fa fa-upload"></i>&nbsp; Image</a>
      {% endif %}
      <div class="clearfix"></div>
      
      <!-- Background -->
      {% if not user.background %}      
      Background:
      <div id="image-filechoice-container">
	<input id="id_background" name="background" type="file">      
      </div>
      <a id="upload_background" class="small button"><i class="fa fa-upload"></i>&nbsp; Image</a>
      {% else %}
      <!-- Background Thumbnail -->
      {% thumbnail user.background "940x78" crop="center" as im %}
          <img src="{{im.url}}"/><br/>
      {% endthumbnail %}	  
      <!-- Repace Background -->
      Background:
      <div id="image-filechoice-container">
	<input id="id_background" name="background" type="file">      
      </div>
      <a id="upload_background" class="small button"><i class="fa fa-upload"></i>&nbsp; Image</a>
      {% endif %}             
      
      <!-- About -->
      {{form.about}}
      <div class="clearfix"></div>        

      <button class="button small right" type="submit">Save</button>	
    </form>
    <a href="/update-password/">Change Password</a>

    <div class="clearfix"></div>
  </div>
</div>

<script>
    $(document).ready(function(){    
	$('#upload').click(function(){
	    $('#id_avatar').click();
    });

	$('#upload_background').click(function(){
	    $('#id_background').click();
	});
    
    })
</script>


{% endblock content %}

digitalverse/templates/profiles/test.html
{% extends "base.html" %}

{% block content %}

<div class="row">
  <div class="large-12 columns">

<form method="post" enctype="multipart/form-data" action=""><input type="hidden" name="csrfmiddlewaretoken" value="6CdgBBUs6pXqSKO5afHytiNHxIRLYyLu">
      <p><label for="id_username">Username:</label> <input id="id_username" maxlength="30" name="username" type="text" value="rayalez"> <span class="helptext">Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.</span></p>
<p><label for="id_avatar">Avatar:</label> <input id="id_avatar" name="avatar" type="file"></p>
      <button class="button small right" type="submit">Save</button>	
    </form>
  </div>
</div>

{% endblock content %}

digitalverse/templates/profiles/update-password.html
{% extends "base.html" %}

{% block content %}

<div class="row">
  <div class="large-12 columns">
    <h1> Update Password </h1>
    <br/>
    {% if message %}
    <div class="panel">{{message}}</div>
    {% endif %}      
    <form method="post" action="/update-password/"> {% csrf_token %}
      Old Password:
      {{form.old_password}}
      New Password:
      {{form.new_password1}}
      Repeat:
      {{form.new_password2}}            
      <button class="button small right" type="submit">Save</button>
    </form>

    <div class="clearfix"></div>
    <div style="width:100%; height: 20px"></div>
  </div>
</div>
{% endblock content %}