digitalverse/hubs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # url(r'^$', views.BrowseView.as_view(), name='post-list'),


    url(r'^create-hub/$', views.HubCreate.as_view(), name='hub-create'),
    url(r'^hub/(?P<slug>[^\.]+)/edit$', views.HubEdit.as_view()),
    url(r'^hub/(?P<slug>[^\.]+)/delete$', views.hub_delete),    

    # url(r'^browse/$', views.BrowseView.as_view(), name='post-list'),

    url(r'^hub/(?P<slug>[^\.]+)/subscribe', views.subscribe),
    url(r'^hub/(?P<slug>[^\.]+)/unsubscribe', views.unsubscribe),    

    
    url(r'^hub/(?P<slug>[^\.]+)$', views.HubView.as_view(), name='hub-detail'),


    url(r'^hubs/', views.HubsBrowse.as_view()),
    
]

digitalverse/lumiverse/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from posts import urls as posts_urls
from videos import urls as videos_urls
from series import urls as series_urls
from hubs import urls as hubs_urls
from profiles import urls as profiles_urls
from comments import urls as comments_urls
# from forum import urls as forum_urls

from .views import about, lumen, rigs

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^about/', about),
    url(r'^lumen/', lumen),
    url(r'^rigs/', rigs),            

    url(r'', include(profiles_urls)),        
    url(r'', include(posts_urls)),
    url(r'', include(videos_urls)),    
    url(r'', include(series_urls)),
    url(r'', include(hubs_urls)),        
    url(r'', include(comments_urls)),
    # url(r'', include(forum_urls)),    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

digitalverse/profiles/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout

from .views import login_or_signup, register, authenticate_user, preferences, update_password, about, subscribe, unsubscribe

urlpatterns = [
    url('^login/$', login_or_signup),
    url(r'^logout/', logout), # , {'next_page':'/'}

    url('^register/$', register),
    url(r'^authenticate/', authenticate_user),

    url(r'^preferences/$', preferences),
    # url(r'^user/(?P<slug>[^\.]+)/preferences$', views.UserEdit.as_view()),    
    url(r'^update-password/$', update_password),

    url(r'^user/(?P<username>[^\.]+)/about$', about),        

    url(r'^user/(?P<username>[^\.]+)/subscribe', subscribe),
    url(r'^user/(?P<username>[^\.]+)/unsubscribe', unsubscribe),    
]

digitalverse/series/urls.py
from django.conf.urls import url

from . import views
from .views import SeriesFeed

urlpatterns = [
    # url(r'^$', views.BrowseView.as_view(), name='post-list'),


    url(r'^create-series/$', views.SeriesCreate.as_view(), name='series-create'),
    url(r'^series/(?P<slug>[^\.]+)/edit$', views.SeriesEdit.as_view()),
    url(r'^series/(?P<slug>[^\.]+)/delete$', views.series_delete),    

    # url(r'^browse/$', views.BrowseView.as_view(), name='post-list'),

    url(r'^series/(?P<slug>[^\.]+)/subscribe', views.subscribe),
    url(r'^series/(?P<slug>[^\.]+)/unsubscribe', views.unsubscribe),    

    url(r'^series/(?P<slug>[^\.]+)/feed/atom/$', SeriesFeed()),        
    
    url(r'^series/(?P<slug>[^\.]+)$', views.SeriesView.as_view(), name='series-detail'),


    url(r'^series/', views.SeriesBrowse.as_view()),
    
]

digitalverse/profiles/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models import permalink

from django.core.files.base import ContentFile
from sorl.thumbnail import ImageField
from sorl.thumbnail import get_thumbnail

# from posts.models import Post
from series.models import Series

class User(AbstractUser):  
    avatar = models.ImageField(upload_to='users/avatars/', default=None,blank=True, null=True)
    background = models.ImageField(upload_to='users/backgrounds/', default=None,blank=True, null=True)
    about = models.TextField(max_length=512, blank=True)
    website = models.CharField(max_length=64, blank=True)
    youtube_channel = models.CharField(max_length=128, blank=True)    

    karma = models.IntegerField(default=0)
    # created = models.DateTimeField(auto_now_add=True, blank=True)

    subscribed = models.ManyToManyField('User', related_name="subscribers", blank=True)
    subscribed_series = models.ManyToManyField('series.Series', related_name="subscribers", blank=True)    

    upvoted = models.ManyToManyField('videos.Video', related_name="upvoters", blank=True)
    posts_upvoted = models.ManyToManyField('posts.Post', related_name="upvoters", blank=True)
    comments_upvoted = models.ManyToManyField('comments.Comment', related_name="upvoters", blank=True)

    newsletter = models.BooleanField(default=False)    
    approved = models.BooleanField(default=False)
    hidden = models.BooleanField(default=False)

    youtube_player = models.BooleanField(default=False)        
    
    # @permalink
    # def get_absolute_url(self):
    #     return ('view_post', None, {'slug': self.slug })        

    # def save(self, slug="", *args, **kwargs):
    #     super(User, self).save(*args, **kwargs)  
    #     resized = get_thumbnail(self.avatar, "120x120", crop='center', quality=99)
    #     self.avatar.save(resized.name, ContentFile(resized.read()), True)            

    #     return super(User, self).save(*args, **kwargs)
    

digitalverse/series/models.py
import itertools
import datetime
from django.utils.timezone import utc

from django.db import models
from django.template.defaultfilters import slugify
from django.conf import settings

from sorl.thumbnail import ImageField

from categories.models import Category

class Series(models.Model):
    title = models.CharField(max_length=256)
    slug = models.SlugField(max_length=256, default="")
    published = models.BooleanField(default=False, blank=True)
    pub_date = models.DateTimeField(auto_now_add=True)

    image = models.ImageField(upload_to='series/avatars/',
                                  default=None,blank=True, null=True)    


    background = models.ImageField(upload_to='series/backgrounds/',
                                   default=None,blank=True, null=True) 

    description = models.TextField(default="", null=True, blank=True)

    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="series", default="")

    categories = models.ManyToManyField('categories.Category', related_name="series", blank=True)
    hubs = models.ManyToManyField('hubs.Hub', related_name="series", blank=True)
    score = models.IntegerField(default=0)
    views = models.IntegerField(default=0)

    
    def __str__(self):
        return self.title

    def save(self, slug="", *args, **kwargs):
        # Slug
        if slug != "":
            self.slug = slug            
        else:
            if self.pk is None:
                self.slug = orig = slugify(self.title)
                # unique_slugify(self, orig) 
                for x in itertools.count(1):
                    if not Series.objects.filter(slug=self.slug).exists():
                        break
                    self.slug = '%s-%d' % (orig, x)            

        # Pub date
        if not self.id:
            self.pub_date = datetime.datetime.now()


        return super(Series, self).save(*args, **kwargs)

digitalverse/profiles/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import User

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=False, widget=forms.TextInput(attrs = {'placeholder': 'E-Mail'})) #reqired=True

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2", "newsletter")
        widgets = {
            'username' : forms.TextInput(attrs = {'placeholder': 'Username'}),
            'email'    : forms.TextInput(attrs = {'placeholder': 'E-Mail'}),
            # 'newsletter'    : forms.CheckboxInput(attrs = {'placeholder': 'E-Mail'}),
            # These don't work, had to redefine in views(login_or_signup)
            # 'password1' : forms.PasswordInput(attrs = {'placeholder': 'Password'}),
            # 'password2' : forms.PasswordInput(attrs = {'placeholder': 'Repeat Password'})
        }

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user
        
class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'newsletter', 'avatar', 'background', 'website', 'youtube_channel', 'about']
        widgets = {
            'username' : forms.TextInput(attrs = {'placeholder': 'Username'}),
            'email'    : forms.TextInput(attrs = {'placeholder': 'E-Mail'}),
            'website'    : forms.TextInput(attrs = {'placeholder': 'Website'}),
            'youtube_channel'    : forms.TextInput(attrs = {'placeholder': 'Youtube Channel Url'}), 
            'about'    : forms.Textarea(attrs = {'placeholder': 'About'}),
        }
    

digitalverse/series/forms.py
from django.forms import ModelForm
from django import forms

from .models import Series

class SeriesForm(ModelForm):
    class Meta:
        model = Series
        fields = ['title', 'image', 'background', 'description', 'hubs']
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Title'}),
            'description': forms.Textarea(attrs={'placeholder': 'Description (optional)',
                                                 'class': 'description',
                                                 'id': 'description'}),
        }

        


        

digitalverse/profiles/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView, UpdateView

from .models import User
from .forms import RegistrationForm, UserForm



def subscribe(request, username):
    userprofile = User.objects.get(username=username)
    if not request.user.is_anonymous():
        user = request.user
        user.subscribed.add(userprofile)
        user.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER')) 
    else:
        return HttpResponseRedirect('/login/')    

def unsubscribe(request, username):
    userprofile = User.objects.get(username=username)    
    user = request.user
    user.subscribed.remove(userprofile)
    user.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER')) 
    

def login_or_signup(request):
    # If already logged in - get out of here
    if request.user.is_authenticated():
        return HttpResponseRedirect('/')

    nextpage = request.GET.get('next', '/')
    authenticate_form = AuthenticationForm(None, request.POST or None)
    # register_form = UserCreationForm()
    register_form = RegistrationForm()
    register_form.fields['password1'].widget.attrs['placeholder'] = "Password"
    register_form.fields['password2'].widget.attrs['placeholder'] = "Repeat Password"        
    return render(request, "profiles/login.html", {
        'authenticate_form': authenticate_form,
        'register_form': register_form,
        'nextpage': nextpage,                
    })


# Only log in
def authenticate_user(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/')
 
    # Initialize the form either fresh or with the appropriate POST data as the instance
    auth_form = AuthenticationForm(None, request.POST or None)
    nextpage = request.GET.get('next', '/')
 
    # The form itself handles authentication and checking
    # to make sure passowrd and such are supplied.
    if auth_form.is_valid():
        login(request, auth_form.get_user())
        return HttpResponseRedirect(nextpage)
 
    return render(request, 'profiles/form-invalid.html', {
        'form': auth_form,
        'title': 'User Login',
        'next': nextpage,
    })

# Only sign up
def register(request):
    rational = False
    if request.META['HTTP_HOST'] == "rationalfiction.io" or \
       request.META['HTTP_HOST'] == "localhost:8000":
        rational = True

    if request.method == 'POST':
        # form = UserCreationForm(request.POST)
        form = RegistrationForm(request.POST)
        if form.is_valid():
            # new_user = form.save()
            user = User.objects.create_user(form.cleaned_data['username'], None, form.cleaned_data['password1'])
            user.email = form.cleaned_data['email']
            user.newsletter = form.cleaned_data['newsletter']            

            user.save()

            # log user in after signig up
            username = request.POST['username']
            password = request.POST['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            
            return HttpResponseRedirect("/")
    else:
        form = UserCreationForm()
    return render(request, "profiles/form-invalid.html", {
        'form': form,
    })


@login_required
def preferences(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login/')

    message = ""    

    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/preferences/')
        else:
            message="error"
    else:
        form = UserForm(instance=request.user)
    
    return render(request, "profiles/preferences.html", {
        'form': form,
        'message':message
    })



# class UserEdit(UpdateView):
#     model = User
#     slug_field = 'username'
#     fields = ["username","avatar"]
#     template_name = 'profiles/test.html'

#     def get_success_url(self):
#         return "/user/rayalez/preferences"
#         # return self.request.path


@login_required
def update_password(request):
    form = PasswordChangeForm(user=request.user)
    message = ""

    if request.method == 'GET':
        if request.GET.get('error')=="1":
            message = "Error, please try again."

    if request.method == 'POST':
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return HttpResponseRedirect('/preferences/')
        else:

            return HttpResponseRedirect('/update-password/?error=1')            
    else:
        form = PasswordChangeForm(user=request.user)

    return render(request, "profiles/update-password.html", {
        'form': form,
        'message':message
    })



def about(request, username):
    userprofile = User.objects.get(username=username)    

    return render(request, 'profiles/about.html',{
        'userprofile':userprofile
    })

digitalverse/templates/series/browse.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}
<title>Series - lumiverse</title>
{% endblock %}


{% block content %}

<style>
.row {
  max-width: 95%!important;
  }
</style>

{# {% include "elements/featured.html" %} #}
{% include "elements/subnav.html" %}

{# {% include "elements/sidebar.html" %} #} <!-- sidebar test -->



<div class="browse-series" style="">
  
{% include "series/series-list.html" %}
  
{% include "elements/subscribe-popup.html" %}  

{% endblock content %}

digitalverse/templates/series/dv-subheader.html
{% load thumbnail %}

<style>
  .username {
  font-family: "Titillium Web";
    font-weight: 100!important;
    font-size: 40px;
  }

    .main-header {
    display:none;
    }
    .username {
    margin-top: 18px!important;
    }
    .stats {
    display:none;
    }

  .subheader {
  padding: 40px 0;
  padding-bottom: 20px;
  }

.tagline {
    padding-left: 60px;
  }

  #browse-template {
    padding-top: 4px;  
  }
    .username {
    margin-top: 18px!important;
    }

    .video-stats, .hubs {
    display:none;
    }

    .comment-section, .post-footer, .moreby {
    display: none;
    }

  
    #browse-template .card-description {
  height: 70px;  
    overflow: hidden;
    }

  
/*
.row {
  width:66%!important;
  }
  .reveal .row {
      width: 100%!important;
  }
*/
  
#browse-template {
    padding-top: 10px!important;
    width: 65%!important;
    margin: auto!important;
}

#browse-template article {
    position: relative;
    width: calc(33.33% - 20px)!important;
    margin: 10px!important;
    float: left;
    background: #222;
  }


body {
    background: #111111;
}  
  #browse-template article {
      background: #1f1f1f;
    }

#browse-template .video-title a {
    color: #13aff0;
color: #dcdcdc;  
}  

  #browse-template .card-description hr {
    display: none;
}
  
</style>


<div class="subheader series-subheader">
       <style>
	 .subheader {
	    background:url("/media/series/backgrounds/learn_junichi.jpg");
	 }
       </style>

  <div class="row">
  <div class="large-6 small-6 columns user-info">
    <a href="/series/digitalverse">
      <img src="/media/cache/48/fd/48fd6a61f5d167ebf2625301d07698e9.png" class="avatar"/>


	  
      <div class="left">
	<h1 class="username"> digitalverse
	</h1>


      </div>
    </a>
  </div>


  <div class="large-6 small-6 columns"> 
    <div class="buttons">

      <!-- 
      <a class="button purchase"
	 href="/series/{{series.slug}}/unsubscribe">
	Purchase (<span>$</span>5)</a>
      -->


      <a class="button" data-open="login-popup">
	Subscribe</a>

      <!-- 
      {% if series.description %}      
      <a class="button"
	 href="/user/{{userprofile}}/about">
	About</a>
      {% endif %}            
      -->

    </div>
  </div>

  <div class="clearfix"></div>

  </div>
  <div class="tagline">
    SideFX Houdini and 3D animation tutorials.
    <!-- 
    <div style="margin:auto;
		width: 70%;
		color: #fefefe";>
    </div>
     -->
  </div>
  
</div>




<div class="reveal" id="login-popup" data-reveal style="padding-bottom: 0;">
  <div class="row">
    
    <div id="mc_embed_signup" style="/* margin-left:60; float: right;*/">
      <form action="//digitalverse.us7.list-manage.com/subscribe/post?u=0f23c7984541d915d1108a16e&amp;id=cd51a6bb9f" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>

        <div class="mc-field-group">

	  <!-- RSS icon -->
	  <span class="rss-icon" style="
					font-size: 32px;
					margin: 0;
					float: right;
					background: #2f3333;
					padding: 5px 10px;
					line-height: 0px;">
	  <a href="https://www.youtube.com/feeds/videos.xml?channel_id=UCrzEUtLCSfHduoy8c-iBPcw">
	      <i class="fi-rss large"></i></a>

	    <!-- 
	    <a href="/series/digitalverse/feed/atom/">
	      <i class="fi-rss large"></i></a>
	     -->
	  </span>


	  <!-- Youtube -->
          <a class="button rss-icon" style="
					font-size: 32px;
					margin: 0;
					float: right;
					background: #2f3333;
					padding: 5px 10px;
					line-height: 0px;
					height: 42px;
					margin-right: 6px;"
	     href="https://www.youtube.com/channel/UCrzEUtLCSfHduoy8c-iBPcw">
	    <i class="fi-social-youtube large"></i></a>


	  
          <input class="required email"
                 id="mce-EMAIL"
                 name="EMAIL"
                 placeholder="Enter your email"
                 type="email"
                 value=""
		 style="/*width: 65%;*/
			width:calc(100% - 50px);
			height: 42px;
			float: left;
			margin: 0;
			width: calc(100% - 220px);"/>
          <input class="small button right"
                 id="subscribeButton"
                 name="subscribe"
                 type="submit"
                 value="Subscribe"
		 style="width:100%;
			width:calc(100% - 50px);
			float:left!important;
			margin-top:4px;
			margin-top: 0;
			height: 42px;
			width: 120px;
			padding: 0;
			background: #2F3333!important;
			"/>
        </div>

        <div class="clear" id="mce-responses">
          <div class="response" id="mce-error-response" style="display:none">&nbsp;</div>
          <div class="response" id="mce-success-response" style="display:none">&nbsp;</div>
        </div>

	<!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_0f23c7984541d915d1108a16e_cd51a6bb9f" tabindex="-1" value=""></div>
    </div>
	

      </form>
    </div>
    
  </div>
</div>

digitalverse/templates/series/edit.html
{% extends "base.html" %}
{% load thumbnail %}

{% block content %}

<div class="row page" id="edit-template">
  <div class="large-12 small-12 columns">
    <br/>
    {{ form.errors }}
    <form action="" enctype="multipart/form-data" method="post">{% csrf_token %}
      {{ form.title }}

      <!-- Image -->
      {% if not series.image %}      
      Avatar:
      <div id="image-filechoice-container">
	<input id="id_image" name="image" type="file">      
      </div>
      <a id="upload" class="small button"><i class="fa fa-upload"></i>&nbsp; Avatar</a>
      {% else %}
      <!-- Image Thumbnail -->
      <div style="width:70px;
		  height:70px;
		  float:left;
		  margin-right:10px;">
	{% thumbnail series.image "70x70" crop="center" as im %}
	    <img src="{{im.url}}"/><br/>
	{% endthumbnail %}	  
      </div>
      <!-- Repace Image -->
      Image:
      <div id="image-filechoice-container"
	   style="width:calc(100% - 80px);">
	<input id="id_image" name="image" type="file">      
      </div>
      <a id="upload" class="small button"><i class="fa fa-upload"></i>&nbsp; Image</a>
      {% endif %}
      <div class="clearfix"></div>
      
      <!-- Background -->
      {% if not series.background %}      
      Background:
      <div id="image-filechoice-container">
	<input id="id_background" name="background" type="file">      
      </div>
      <a id="upload_background" class="small button"><i class="fa fa-upload"></i>&nbsp; Background</a>
      {% else %}
      <!-- Background Thumbnail -->
      {% thumbnail series.background "940x78" crop="center" as im %}
          <img src="{{im.url}}"/><br/>
      {% endthumbnail %}	  
      <!-- Repace Background -->
      Background:
      <div id="image-filechoice-container">
	<input id="id_background" name="background" type="file">      
      </div>
      <a id="upload_background" class="small button"><i class="fa fa-upload"></i>&nbsp; Background</a>
      {% endif %}             

      <!-- {{ form.thumbnail }} -->

      <textarea class="description" cols="40" id="description" name="description" placeholder="Description (optional)" rows="10"></textarea>


      <div class="clearfix"></div>
	<div class="set-categories">
	  {{form.hubs}}
	</div>
	<br/>
      

      {% if not creating %}
	<a class="button delete" data-open="delete">Delete</a>	
      {% endif %}


<div class="reveal" id="delete" data-reveal>
	<b> Confirm </b>
	<p class="lead">Are you sure you want to delete this series?</p>

	<button class="close-button" data-close aria-label="Close modal" type="button">
	  <span aria-hidden="true">&times;</span>
	</button>    
	
	<a class="button" href="/series/{{series.slug}}/delete">Delete</a>	
</div>
      

      
      <div class="right">
	{% if not creating %}
            <a class="button" href="/series/{{series.slug}}">View</a>		    
    	    <!-- {% if not post.published or True %} -->
            <!-- <a class="button" href="/series/{{series.slug}}">Preview</a> -->
            <!-- <a class="button" href="/post/{{post.slug}}/publish">Publish</a> -->
            <!-- {% else %} -->
            <!-- <a class="button" href="/series/{{series.slug}}">View</a>		     -->
            <!-- <a class="button" href="/post/{{post.slug}}/unpublish">Unpublish</a>	 -->
            <!-- {% endif %} -->
        {% endif %}
	    
	<input type="submit" value="Save" />
	<br/>
      </div>
      
    </form>

  </div>
</div>


<!-- Select2 -->
<link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css" rel="stylesheet" />
<script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js"></script>

<script>
    $(document).ready(function(){    
	$('#upload').click(function(){
	    $('#id_image').click();
	});

	$('#upload_background').click(function(){
	    $('#id_background').click();
    });

    // Multiselect
    $("#id_hubs").select2({
	placeholder: "Select hubs", // (maximum 4)
	allowClear: true,
	maximumSelectionLength: 2    
    })
    
	
    })
</script>

{% endblock content %}

digitalverse/templates/series/pagination.html
<div class="clearfix"></div>	
{% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a class="button small prev-page"
		       href="{{request.path}}?page={{ page_obj.previous_page_number }}{% if sorting %}&sorting={{sorting}}{% endif %}{% if category %}&category={{category}}{% endif %}">
		      < previous page</a>
                {% endif %}
		    <!-- 
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
		-->

                {% if page_obj.has_next %}
                    <a class="button small next-page"
		       href="{{request.path}}?page={{ page_obj.next_page_number }}{% if sorting %}&sorting={{sorting}}{% endif %}{% if category %}&category={{category}}{% endif %}">
		      next page ></a>
                {% endif %}
            </span>
        </div>
<div class="clearfix"></div>	
        {% if page_obj.has_previous and page_obj.has_next  %}
	<style>
	  .page-links a {
	  width: 50%!important;
	  }
	</style>
        {% endif %}
    {% endif %}

digitalverse/templates/series/profile.html
{% extends "base.html" %}
{% load thumbnail %}

{% block content %}

{% include "elements/subheader.html" %}
{% include "elements/subnav.html" %}


<div id="browse-template" class="page">
  
{% for post in object_list %}
{% if post.published or user == post.author %}  
  <a href="{{post.get_absolute_url}}">  
    <article>
      
    <img src="/media/{{post.thumbnail}}" />

    <div class="dark-overlay">

      <b style="float:left;">{{post.title}} </b>
      {% if user == post.author or user.is_staff  %}
      <a class="edit-post margins-0" href="/post/{{post.slug}}/edit">
	<i class="fa fa-pencil"></i></a>

          {% if not post.published %}        
          <span class="right margins-side-10">[unpublished]</span>
	  {% endif %}        
      {% endif %}
    </div>
    </article>
  </a>
{% endif %}  
{% endfor %}
</div>
{% include "posts/pagination.html" %}  
<style>
  .row {
  max-width: 95%!important;
  }
</style>
{% endblock content %}

digitalverse/templates/series/series.html
{% extends "base.html" %}
{% load thumbnail %}


{% block title %}
<title>{{series.title}} - lumiverse</title>
{% endblock %}



{% block content %}


{% if request.META.HTTP_HOST == "orangemind.lumiverse.io" %}  
    {% include "elements/orangemind-header.html" %}
{% elif request.META.HTTP_HOST == "digitalverse.io" or  request.META.HTTP_HOST == "localhost:8000" %}  
    {% include "series/dv-subheader.html" %}
{% else  %}
    {% include "series/subheader.html" %}
{% endif %}

<div id="browse-template" class="page">

  {% include "videos/video-list.html" %}  

<style>
  .row {
  max-width: 95%!important;
  }
</style>
{% endblock content %}