digitalverse/hubs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # url(r'^$', views.BrowseView.as_view(), name='post-list'),


    url(r'^create-hub/$', views.HubCreate.as_view(), name='hub-create'),
    url(r'^hub/(?P<slug>[^\.]+)/edit$', views.HubEdit.as_view()),
    url(r'^hub/(?P<slug>[^\.]+)/delete$', views.hub_delete),    

    # url(r'^browse/$', views.BrowseView.as_view(), name='post-list'),

    url(r'^hub/(?P<slug>[^\.]+)/subscribe', views.subscribe),
    url(r'^hub/(?P<slug>[^\.]+)/unsubscribe', views.unsubscribe),    

    
    url(r'^hub/(?P<slug>[^\.]+)$', views.HubView.as_view(), name='hub-detail'),


    url(r'^hubs/', views.HubsBrowse.as_view()),
    
]

digitalverse/posts/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView


from . import views
# from .feeds import MainFeed

urlpatterns = [

    # User Feed
    # url(r'^user/(?P<username>[^\.]+)/feed/atom/$', feeds.UserFeed()),    

    # Blog at the home page
    url(r'^$', views.BlogView.as_view()),    


    # Class Based Views
    # Browse
    url(r'^forum/$', views.BrowseView.as_view()),
    url(r'^community/$', views.BrowseView.as_view()),
    url(r'^blog/$', views.BlogView.as_view()),            
    url(r'^profile/(?P<username>[^\.]+)$', views.UserprofileView.as_view()),
    # url(r'^forum/category/(?P<hubslug>[^\.]+)/$', views.HubView.as_view()),
    

    # CRUD Posts
    url(r'^post/add$', views.post_create),
    url(r'^post/(?P<slug>[^\.]+)/edit$', views.post_edit),
    url(r'^post/(?P<post>[^\.]+)/delete$', views.post_delete),
    url(r'^post/(?P<slug>[^\.]+)/?$', views.post, name='view_post'),



    url(r'^post-upvote/$', views.upvote),
    url(r'^post-unupvote/$', views.unupvote),

    # Comments
    # url(r'^forum/(?P<post>[^\.]+)/comment-submit$', views.comment_submit),
    # url(r'^forum/comment/(?P<comment_id>[^\.]+)/reply-submit', views.reply_submit),    
    # url(r'^forum/comment/(?P<comment_id>[^\.]+)/edit', views.comment_edit),
    # url(r'^forum/comment/(?P<comment_id>[^\.]+)/delete', views.comment_delete), 

    # url(r'^comment-upvote/', views.comment_upvote),
    # url(r'^comment-unupvote/', views.comment_unupvote),
    

    # url(r'^user/(?P<username>[^\.]+)/comments$', views.comments_user,
    #     {'filterby': 'comments_user'}),



    # url(r'^upvote/$', views.upvote),
    # url(r'^unupvote/$', views.unupvote),


]

digitalverse/profiles/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout

from .views import login_or_signup, register, authenticate_user, preferences, update_password, about, subscribe, unsubscribe

urlpatterns = [
    url('^login/$', login_or_signup),
    url(r'^logout/', logout), # , {'next_page':'/'}

    url('^register/$', register),
    url(r'^authenticate/', authenticate_user),

    url(r'^preferences/$', preferences),
    # url(r'^user/(?P<slug>[^\.]+)/preferences$', views.UserEdit.as_view()),    
    url(r'^update-password/$', update_password),

    url(r'^user/(?P<username>[^\.]+)/about$', about),        

    url(r'^user/(?P<username>[^\.]+)/subscribe', subscribe),
    url(r'^user/(?P<username>[^\.]+)/unsubscribe', unsubscribe),    
]

digitalverse/videos/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    # Store
    url(r'^user/rayalez/store/$', views.item),
    
    url(r'^$', views.BrowseView.as_view(), name='video-list'),
    url(r'^videos/$', views.BrowseView.as_view(), name='video-list'),    
    url(r'^browse/$', views.BrowseView.as_view(), name='video-list'),    
    url(r'^subscriptions/$', views.SubscriptionsView.as_view(), name='subscriptions'),    


    url(r'^user/(?P<username>[^\.]+)/feed/atom/$', views.UserFeed()),    

    url(r'^user/(?P<username>[^\.]+)?/$', views.ProfileView.as_view(), name='profile'),
    url(r'^user/(?P<username>[^\.]+)$', views.ProfileView.as_view(), name='profile'),
    


    # url(r'^upload/$', views.VideoCreate.as_view(), name='video-create'),
    url(r'^upload/$', views.video_create, name='video-create'),    
    # url(r'^video/(?P<slug>[^\.]+)/edit$', views.VideoEdit.as_view()),
    url(r'^video/(?P<slug>[^\.]+)/edit$', views.video_edit),    
    url(r'^video/(?P<slug>[^\.]+)/delete$', views.video_delete),    
    url(r'^video/(?P<slug>[^\.]+)/publish$', views.video_publish),
    url(r'^video/(?P<slug>[^\.]+)/unpublish$', views.video_unpublish),        
    url(r'^video/(?P<slug>[^\.]+)$', views.VideoDetailView.as_view(), name='video-detail'),

    url(r'^test/$', views.testview, name='video-create'),

    url(r'^upvote/$', views.upvote),
    url(r'^unupvote/$', views.unupvote),
    
]

digitalverse/posts/models.py
import datetime
import uuid

from django.db import models
from django.db.models import permalink
from django.conf import settings
from django.template.defaultfilters import slugify


class Post(models.Model):
    title = models.CharField(max_length=256)
    slug = models.SlugField(max_length=256, default="")
    published = models.BooleanField(default=True, blank=True)
    pub_date = models.DateTimeField(blank=True)
    # updated = models.DateTimeField(default=datetime.datetime.now, blank=True)    
    body = models.TextField(default="", null=True, blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="posts", default="")

    categories = models.ManyToManyField('Category', related_name="posts", blank=True)
    score = models.IntegerField(default=0)
    views = models.IntegerField(default=0)


    dvblog = models.BooleanField(default=False, blank=True)
    
    def __str__(self):
        return self.title

    def save(self, slug="", *args, **kwargs):
        if not self.id:
            self.pub_date = datetime.datetime.now()


        # Unique slug
        if self.pk is None:            
            if slug:
                # If I'm passing a slug - just use it.
                # As it stands - don't need it, I'm never editing it once created.
                self.slug = slug            
            else:
                # If not - slugify title
                self.slug = orig = slugify(self.title)
                # Come up with unique id
                while True:
                    # If the post is unique now - it's done, if not - come up with another one
                    if not Post.objects.filter(slug=self.slug).exists():
                        break
                    # Generate random id
                    uniqueid = uuid.uuid1().hex[:5]
                    self.slug = orig + "-" + str(uniqueid)
                    

        return super(Post, self).save(*args, **kwargs)
    
    @permalink
    def get_absolute_url(self):
        return ('view_post', None, {'slug': self.slug })


class Category(models.Model):
    title = models.CharField(max_length=64)    
    slug = models.SlugField(max_length=64, default="")
    # description = models.TextField(max_length=512, blank=True)
    # order = models.IntegerField(default=0)
    
    def __str__(self):
        return self.title        

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Category, self).save(*args, **kwargs)
    

digitalverse/videos/models.py
import itertools
import datetime
from django.utils.timezone import utc

from django.db import models
from django.template.defaultfilters import slugify
from django.conf import settings
from django.db.models import permalink
from django.core.files.base import ContentFile

from sorl.thumbnail import ImageField
from sorl.thumbnail import get_thumbnail


from categories.models import Category
from series.models import Series

from .utils import rank_hot,next_or_prev_in_order #, unique_slugify

def generate_filename(self,filename):
    url = "videos/%s/%s" % (self.author.username,filename)
    return url

class Video(models.Model):
    title = models.CharField(max_length=256)
    slug = models.SlugField(max_length=256, default="")
    published = models.BooleanField(default=False, blank=True)
    pub_date = models.DateTimeField(auto_now_add=True)

    video = models.FileField(upload_to=generate_filename, default=None,blank=True, null=True)
    thumbnail = models.ImageField(upload_to='videos/thumbnails/',
                                  default=None,blank=True, null=True)

    video_url = models.CharField(max_length=256, default="", blank=True, null=True)
    
    description = models.TextField(default="", null=True, blank=True)

    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="videos", default="")

    categories = models.ManyToManyField('categories.Category', related_name="videos", blank=True)

    hubs = models.ManyToManyField('hubs.Hub', related_name="videos",
                            default=None, blank=True)


    series = models.ForeignKey('series.Series', related_name="videos",
                               default=None, blank=True, null=True)

    
    score = models.IntegerField(default=0)
    views = models.IntegerField(default=0)

    digitalverse = models.BooleanField(default=False)    

    def __str__(self):
        return self.title

    # def get_thumb(self):
    #     im = get_thumbnail(self.image, '200x200', crop='center', quality=99)
    #     return im.url # remember that sorl objects have url/width/height attributes    

    
    def save(self, slug="", *args, **kwargs):
        # Slug
        if slug != "":
            self.slug = slug            
        else:
            if self.pk is None:
                self.slug = orig = slugify(self.title)
                # unique_slugify(self, orig) 
                for x in itertools.count(1):
                    if not Video.objects.filter(slug=self.slug).exists():
                        break
                    self.slug = '%s-%d' % (orig, x)            

        # Pub date
        if not self.id:
            self.pub_date = datetime.datetime.now()

        # Create thumbnail
        # if not self.id:  
        # super(Video, self).save(*args, **kwargs)
        # resized = get_thumbnail(image.image, "400x400", crop='center', quality=99)
        # self.thumbnail.save(resized.name, ContentFile(resized.read()), True)            

        return super(Video, self).save(*args, **kwargs)


    def prev_by_author(self, loop=False):
        qs = Video.objects.filter(series=self.series, published=True)# .order_by('-pub_date')
        return next_or_prev_in_order(self, True, qs)

    def next_by_author(self, loop=False):
        qs = Video.objects.filter(series=self.series, published=True)# .order_by('-pub_date')
        return next_or_prev_in_order(self, False, qs)

    @permalink
    def get_absolute_url(self):
        return ('video-detail', None, {'slug': self.slug })

    class Meta:
        ordering = ["pub_date"]    

digitalverse/posts/forms.py
import itertools

from django.forms import ModelForm
from django import forms
from django.template.defaultfilters import slugify

from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body'] # , 'hubs'
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Title'}),
            'body': forms.Textarea(attrs={'class': 'markdown',
                                          'id': 'markdown'}),            
        }

digitalverse/videos/forms.py
from django.forms import ModelForm
from django import forms

from .models import Video
from series.models import Series


class VideoForm(ModelForm):

    class Meta:
        model = Video
        fields = ['title', 'video','video_url', 'thumbnail', 'description', 'hubs', 'series']
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Title'}),
            'description': forms.Textarea(attrs={'placeholder': 'Description (optional)',
                                                 'class': 'description',
                                                 'id': 'description'}),
            'video_url': forms.TextInput(attrs={'placeholder': 'Youtube video url'}),            
        }

        



    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(VideoForm, self).__init__(*args, **kwargs)
        self.fields['series'].empty_label = "Select Series"

        self.fields['series'].queryset = Series.objects.filter(author=user)

digitalverse/profiles/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView, UpdateView

from .models import User
from .forms import RegistrationForm, UserForm



def subscribe(request, username):
    userprofile = User.objects.get(username=username)
    if not request.user.is_anonymous():
        user = request.user
        user.subscribed.add(userprofile)
        user.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER')) 
    else:
        return HttpResponseRedirect('/login/')    

def unsubscribe(request, username):
    userprofile = User.objects.get(username=username)    
    user = request.user
    user.subscribed.remove(userprofile)
    user.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER')) 
    

def login_or_signup(request):
    # If already logged in - get out of here
    if request.user.is_authenticated():
        return HttpResponseRedirect('/')

    nextpage = request.GET.get('next', '/')
    authenticate_form = AuthenticationForm(None, request.POST or None)
    # register_form = UserCreationForm()
    register_form = RegistrationForm()
    register_form.fields['password1'].widget.attrs['placeholder'] = "Password"
    register_form.fields['password2'].widget.attrs['placeholder'] = "Repeat Password"        
    return render(request, "profiles/login.html", {
        'authenticate_form': authenticate_form,
        'register_form': register_form,
        'nextpage': nextpage,                
    })


# Only log in
def authenticate_user(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/')
 
    # Initialize the form either fresh or with the appropriate POST data as the instance
    auth_form = AuthenticationForm(None, request.POST or None)
    nextpage = request.GET.get('next', '/')
 
    # The form itself handles authentication and checking
    # to make sure passowrd and such are supplied.
    if auth_form.is_valid():
        login(request, auth_form.get_user())
        return HttpResponseRedirect(nextpage)
 
    return render(request, 'profiles/form-invalid.html', {
        'form': auth_form,
        'title': 'User Login',
        'next': nextpage,
    })

# Only sign up
def register(request):
    rational = False
    if request.META['HTTP_HOST'] == "rationalfiction.io" or \
       request.META['HTTP_HOST'] == "localhost:8000":
        rational = True

    if request.method == 'POST':
        # form = UserCreationForm(request.POST)
        form = RegistrationForm(request.POST)
        if form.is_valid():
            # new_user = form.save()
            user = User.objects.create_user(form.cleaned_data['username'], None, form.cleaned_data['password1'])
            user.email = form.cleaned_data['email']
            user.newsletter = form.cleaned_data['newsletter']            

            user.save()

            # log user in after signig up
            username = request.POST['username']
            password = request.POST['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            
            return HttpResponseRedirect("/")
    else:
        form = UserCreationForm()
    return render(request, "profiles/form-invalid.html", {
        'form': form,
    })


@login_required
def preferences(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login/')

    message = ""    

    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/preferences/')
        else:
            message="error"
    else:
        form = UserForm(instance=request.user)
    
    return render(request, "profiles/preferences.html", {
        'form': form,
        'message':message
    })



# class UserEdit(UpdateView):
#     model = User
#     slug_field = 'username'
#     fields = ["username","avatar"]
#     template_name = 'profiles/test.html'

#     def get_success_url(self):
#         return "/user/rayalez/preferences"
#         # return self.request.path


@login_required
def update_password(request):
    form = PasswordChangeForm(user=request.user)
    message = ""

    if request.method == 'GET':
        if request.GET.get('error')=="1":
            message = "Error, please try again."

    if request.method == 'POST':
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return HttpResponseRedirect('/preferences/')
        else:

            return HttpResponseRedirect('/update-password/?error=1')            
    else:
        form = PasswordChangeForm(user=request.user)

    return render(request, "profiles/update-password.html", {
        'form': form,
        'message':message
    })



def about(request, username):
    userprofile = User.objects.get(username=username)    

    return render(request, 'profiles/about.html',{
        'userprofile':userprofile
    })

digitalverse/templates/videos/browse.html
{% extends "base.html" %}
{% load thumbnail %}

{% block content %}
<style>
  .row {
  max-width: 95%!important;
  }
</style>

{% if not hub %}
{% include "elements/featured.html" %}
{% endif %}
{# {% include "elements/subnav.html" %} #}

{# {% include "elements/sidebar.html" %} #} <!-- sidebar test -->



<div id="browse-template" class="page" style="">

<h1 class="section-header"> Recent uploads </h1>

{% include "videos/video-list.html" %}


{% include "elements/subscribe-popup.html" %}  


{% endblock content %}

digitalverse/templates/videos/edit.html
{% extends "base.html" %}

{% block content %}

<div class="row page" id="edit-template">
  <div class="large-12 small-12 columns">
    <br/>
{% if not user.is_staff and not user.approved %}
    <h1>Invite required</h1>
    <p>Hi! lumiverse is still in beta, and to upload videos you need an invite, sorry about that.</p>

    <p>To receive an invite, send me a message to raymestalez@gmail.com, with a few examples of videos that you are planning to upload.</p>    
{% else %}

    {{ form.errors }}
    <form action="" enctype="multipart/form-data" method="POST">{% csrf_token %}
      {{ form.title }}



      <!-- Upload -->
      {% if not video.video and not video.video_url %}
      <!-- Tabs -->
      <ul class="tabs" data-tabs id="upload-tabs">
	<li class="tabs-title"><a href="#panel1">Upload</a></li>
	<li class="tabs-title is-active"><a href="#panel2" aria-selected="true">Youtube</a></li>
      </ul>


      <div class="tabs-content" data-tabs-content="upload-tabs">
	<div class="tabs-panel" id="panel1">
	  <!-- Upload Video -->
	  <div id="image-filechoice-container">
	    <input id="id_video" name="video" type="file">
	  </div>
	  <a id="upload" class="images small button"><i class="fa fa-upload"></i>&nbsp; Video</a>
	  <div class="clearfix"></div>            
	</div>
	<div class="tabs-panel  is-active" id="panel2">
	  <!-- From youtube -->
	  {{ form.video_url }}
	</div>
      </div>

      
      {% else %}
          {% if video.video %}
          <!-- Video -->
          <div style="">
          <video id="video" class="video-js vjs-default-skin vjs-big-play-centered"
          	     controls preload="auto" width="850" height="auto"
          	     poster="/media/{{video.thumbnail}}" data-setup='{"fluid":true,}'>
          	<source src="/media/{{video.video}}" type='video/mp4'>
          </video>
          
          	Replace Video:
          	<div id="image-filechoice-container">
          	  <input id="id_video" name="video" type="file" multiple>
          	</div>
          	<a id="upload" class="images small button">
          	  <i class="fa fa-upload"></i>&nbsp; Video</a>
          </div>
          <!-- Thumbnail -->
          <div style="float:right;width:300px;">
          	<img src="/media/{{video.thumbnail}}" style="margin:auto;
          						    max-width:300px;
          						    max-height:300px;"/><br/>
          	<!-- Replace Thumbnail --><!-- <br/>(square, at least 500x500px): -->
          	<div id="image-filechoice-container">      
          	  <input id="id_thumbnail" name="thumbnail" type="file"> {# {{form.thumbnail}}#}
          	</div>
          	<a id="upload_thumbnail" class="small button">
          	  <i class="fa fa-upload"></i>&nbsp; Thumbnail</a>
          </div>
	  {% else %}
	  <video
	     id="video"
	     class="video-js vjs-default-skin  vjs-big-play-centered"
	     controls
	     width="850" height="477"
	     data-setup='{ "techOrder": ["youtube"], "fluid":true,
	     "sources": [{ "type": "video/youtube",
	     "src": "{{video.video_url}}"}] }'>
	  </video>
	  Youtube video url:
	  {{ form.video_url }}	  
	  {% endif %}	  
      {% endif %}      




      {% if creating %}
      <textarea class="description" cols="40" id="description" name="description" placeholder="Description (optional)" rows="10"></textarea>
      {% else %}

          {% if video.video %}      
          <textarea class="description" cols="40" id="description" name="description" placeholder="Description (optional)" rows="10" style="float:left; width: calc(100% - 310px);height:348px;">{{video.description}}</textarea>
	  {% else %}
          <textarea class="description" cols="40" id="description" name="description" placeholder="Description (optional)" rows="10" style="float:left; height:348px;">{{video.description}}</textarea>	  
	  {% endif %}
      {% endif %}
      

      <div class="clearfix"></div>
      <div class="set-categories"
	   style="{% if user.series.all %}width: calc(100% - 310px);float:left{% endif %}">
	{{form.hubs}}
      </div>

      <!-- <input type="text" placeholder="category"> -->
      <!-- <input id="id_series" maxlength="256" name="series" type="text" -->
      <!-- 	     style="float:right;width:36%;" -->
      <!-- 	     placeholder="series"> -->


      {% if user.series.all %}      
      <div class="set-series">
	  {{form.series}}      
      </div>
      {% endif %}            

      <div class="clearfix"></div>      
      <br/>

      {% if not creating %}
      <a class="button delete" data-open="delete">Delete</a>
      {% endif %}

<div class="reveal" id="delete" data-reveal>
	<b> Confirm </b>
	<p class="lead">Are you sure you want to delete this video?</p>

	<button class="close-button" data-close aria-label="Close modal" type="button">
	  <span aria-hidden="true">&times;</span>
	</button>    
	
	<a class="button" href="/video/{{video.slug}}/delete">Delete</a>
</div>
      
      
      <div class="right">
	{% if not creating %}
    	    {% if not video.published %}
            <a class="button" href="/video/{{video.slug}}">Preview</a>	
            <a class="button" href="/video/{{video.slug}}/publish">Publish</a>
            {% else %}
            <a class="button" href="/video/{{video.slug}}">View</a>		    
            <a class="button" href="/video/{{video.slug}}/unpublish">Unpublish</a>	
            {% endif %}
        {% endif %}
	<input type="submit" value="Save" />
	<br/>
      </div>
      
    </form>

{% endif %} <!-- end invite -->




  </div>
</div>

<style>
  .tabs-panel #upload {
  width:133px!important;
  }

</style>

<!-- Select2 -->
<link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css" rel="stylesheet" />
<script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js"></script>

<script>
    $(document).ready(function(){    
	$('#upload').click(function(){
	    $('#id_video').click();
	});

	$('#upload_thumbnail').click(function(){
	    $('#id_thumbnail').click();
    });

    // Multiselect
    $("#id_hubs").select2({
	placeholder: "Select hubs", // (maximum 4)
	allowClear: true,
	maximumSelectionLength: 2    
    })
    
	
    })
</script>



{% endblock content %}

digitalverse/templates/videos/edit_back.html
{% extends "base.html" %}

{% block content %}

<div class="row page" id="edit-template">
  <div class="large-12 small-12 columns">
    <br/>


    {{ form.errors }}
    <form action="" enctype="multipart/form-data" method="POST">{% csrf_token %}
      {{ form.title }}

      
      {% if not video.video %}      
      <div id="image-filechoice-container">
	<input id="id_video" name="video" type="file">
      </div>
      <a id="upload" class="images small button"><i class="fa fa-upload"></i>&nbsp; Video</a>
      <div class="clearfix"></div>            
      
      {% else %}

      <!-- Video -->
      <div style="">
      <video id="video" class="video-js vjs-default-skin vjs-big-play-centered"
	     controls preload="auto" width="850" height="auto"
	     poster="/media/{{video.thumbnail}}" data-setup="{}">
	<source src="/media/{{video.video}}" type='video/mp4'>
      </video>

	Replace Video:
	<div id="image-filechoice-container">
	  <input id="id_video" name="video" type="file" multiple>
	</div>
	<a id="upload" class="images small button">
	  <i class="fa fa-upload"></i>&nbsp; Image</a>
      </div>
      <!-- Thumbnail -->
      <div style="float:right;width:300px;">
	<img src="/media/{{video.thumbnail}}" style="margin:auto;
						    max-width:300px;
						    max-height:300px;"/><br/>
	<!-- Replace Thumbnail --><!-- <br/>(square, at least 500x500px): -->
	<div id="image-filechoice-container">      
	  <input id="id_thumbnail" name="thumbnail" type="file"> {# {{form.thumbnail}}#}
	</div>
	<a id="upload_thumbnail" class="small button">
	  <i class="fa fa-upload"></i>&nbsp; Thumbnail</a>
      </div>

      {% endif %}      

      <p>or:</p>
      {{ form.video_url }}


      {% if creating %}
      <textarea class="description" cols="40" id="description" name="description" placeholder="Description (optional)" rows="10"></textarea>
      {% else %}      
      <textarea class="description" cols="40" id="description" name="description" placeholder="Description (optional)" rows="10" style="float:left; width: calc(100% - 310px);height:348px;">{{video.description}}</textarea>
      {% endif %}
      

      <div class="clearfix"></div>
      <div class="set-categories"
	   style="{% if user.series.all %}width: calc(100% - 310px);float:left{% endif %}">
	{{form.categories}}
      </div>

      <!-- <input type="text" placeholder="category"> -->
      <!-- <input id="id_series" maxlength="256" name="series" type="text" -->
      <!-- 	     style="float:right;width:36%;" -->
      <!-- 	     placeholder="series"> -->


      {% if user.series.all %}      
      <div class="set-series">
	  {{form.series}}      
      </div>
      {% endif %}            

      <div class="clearfix"></div>      
      <br/>

      {% if not creating %}
      <a class="button delete" href="/video/{{video.slug}}/delete">Delete</a>
      {% endif %}
      
      <div class="right">
	{% if not creating %}
    	    {% if not video.published %}
            <a class="button" href="/video/{{video.slug}}">Preview</a>	
            <a class="button" href="/video/{{video.slug}}/publish">Publish</a>
            {% else %}
            <a class="button" href="/video/{{video.slug}}">View</a>		    
            <a class="button" href="/video/{{video.slug}}/unpublish">Unpublish</a>	
            {% endif %}
        {% endif %}
	<input type="submit" value="Save" />
	<br/>
      </div>
      
    </form>

  </div>
</div>


<!-- Select2 -->
<link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css" rel="stylesheet" />
<script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js"></script>

<script>
    $(document).ready(function(){    
	$('#upload').click(function(){
	    $('#id_video').click();
	});

	$('#upload_thumbnail').click(function(){
	    $('#id_thumbnail').click();
    });

    // Multiselect
    $("#id_categories").select2({
	placeholder: "Select categories", // (maximum 4)
	allowClear: true,
	maximumSelectionLength: 2    
    })
    
	
    })
</script>

{% endblock content %}

digitalverse/templates/videos/pagination.html
<div class="clearfix"></div>	
{% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a class="button small prev-page"
		       href="{{request.path}}?page={{ page_obj.previous_page_number }}{% if sorting %}&sorting={{sorting}}{% endif %}{% if category %}&category={{category}}{% endif %}">
		      < previous page</a>
                {% endif %}
		    <!-- 
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
		-->

                {% if page_obj.has_next %}
                    <a class="button small next-page"
		       href="{{request.path}}?page={{ page_obj.next_page_number }}{% if sorting %}&sorting={{sorting}}{% endif %}{% if category %}&category={{category}}{% endif %} ">
		      next page ></a>
                {% endif %}
            </span>
        </div>
<div class="clearfix"></div>	
        {% if page_obj.has_previous and page_obj.has_next  %}
	<style>
	  .page-links a {
	  width: 50%!important;
	  }
	</style>
        {% endif %}
    {% endif %}

digitalverse/templates/videos/profile.html
{% extends "base.html" %}
{% load thumbnail %}


{% block title %}
<title>{{userprofile.username}} - lumiverse</title>
{% endblock %}



{% block content %}


<style>
  .row {
  max-width: 95%!important;
  }
</style>

{% include "elements/subheader.html" %}
{% include "elements/subnav.html" %}


<div id="browse-template" class="page">

{% include "videos/video-list.html" %}
{% endblock content %}